[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv-rt = "0.12.2"
panic-halt = "0.2.0"

[profile.dev]
panic="abort"
strip = true

[profile.dev.package."*"]
opt-level = "z"

[profile.release]
panic="abort"
opt-level = "s"
debug = false
strip = true
